language: python
dist: xenial
python:
  - "3.5"

virtualenv:
  system_site_packages: true
  
before_install:
  - sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo apt-get update
  - sudo apt-get install -y r-base python3-numpy
  - sudo R CMD INSTALL mlds/CRAN/MLDS_0.4.1.tar.gz
  - sudo R CMD INSTALL mlds/CRAN/psyphy_0.1-9.tar.gz

  
# command to install dependencies
install: 
  - pip3 install rpy2

# command to run tests
script: 
  - cd mlds/test
  - nosetests
